import Head from "next/head";
import Header from "../../components/Header";
import MovieDetails from "../../components/MovieDetails";
import Nav from "../../components/Nav";

const API_KEY = process.env.API_KEY;

function MovieId({ results }) {
  console.log(results);

  // if (results.success === false) {
  //   // return <div>Not found</div>;
  //   return { notFound: true };
  // }

  return (
    <div>
      <Head>
        <title>Movie DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Movie Details */}
      <MovieDetails results={results} />
    </div>
  );
}

// https://api.themoviedb.org/3/movie/{movie_id}?api_key=<<api_key>>&language=en-US

export const getStaticPaths = async () => {
  return {
    paths: [], //indicates that no page needs be created at build time
    fallback: "blocking", //indicates the type of fallback "blocking"
  };
};

export async function getStaticProps(context) {
  const id = context.params.id;

  const res = await fetch(
    `https://api.themoviedb.org/3/movie/${id}?api_key=${API_KEY}`
  );

  const resVideo = await fetch(
    `https://api.themoviedb.org/3/movie/${id}/videos?api_key=${API_KEY}&language=en-US`
  );

  const data = await res.json();
  const dataVideo = await resVideo.json();

  data.video = dataVideo;

  if (data.success === false) {
    return { notFound: true };
  } else {
    return {
      props: {
        results: data,
      },
    };
  }
}

// https://api.themoviedb.org/3/movie/{movie_id}/videos?api_key=<<api_key>>&language=en-US
// https://api.themoviedb.org/3/movie/${id}/videos?api_key=${API_KEY}&language=en-US

export default MovieId;
