import Head from "next/head";
import Header from "../../components/Header";
import Nav from "../../components/Nav";
import Results from "../../components/Results";
import requests from "../../utils/requestsHeader";

export default function TopRated({ results }) {
  return (
    <div>
      <Head>
        <title>Movie DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      <Results results={results} />
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    `https://api.themoviedb.org/3${requests.fetchTopRated.url}`
  );
  const data = await res.json();

  return {
    props: {
      results: data.results,
    },
  };
}
